### ISSUE TITLE
Timezone Example not working with Node.js

### ISSUE THREAD

**Issue by ramsingla** [Esri/Terraformer#136]
Using Node v0.10.15 and after setting up the module dependencies.

```
├── terraformer@0.2.0
├─┬ terraformer-arcgis-parser@0.1.8
│ └── terraformer@0.1.7
├─┬ terraformer-geostore@0.1.1
│ └── terraformer@0.1.7
├─┬ terraformer-rtree@0.2.5
│ └── terraformer@0.1.7
├─┬ terraformer-wkt-parser@0.1.8
│ └── terraformer@0.1.7
```
I get the following error on
 
```
> node timezone.js
var dfd = new Terraformer.Deferred();
                ^
TypeError: undefined is not a function

TypeError: undefined is not a function
    at insert (/usr/local/lib/node_modules/terraformer-rtree/index.js:673:17)
    at Object.<anonymous> (/Users/abc/Workspace/terraserv/timezone.js:38:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

Let me know how to fix this issue.

**Comment by jgravois** [comment]
confirmed fixed in #263.  happy to chat more if you have additional questions.
